name: flutter_locatrip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  calendar_date_picker2: ^1.1.8

  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2

  intl: ^0.20.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
  plugin:
    platforms:
      ios:
        pluginClass: AppDelegate