name: flutter_locatrip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  calendar_date_picker2: ^1.1.8

  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.5
  permission_handler: ^11.3.1
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2
  kakao_flutter_sdk_auth: ^1.9.6
  kakao_flutter_sdk_user: ^1.9.6
  


  intl: ^0.20.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  easy_image_viewer: ^1.5.1
  url_launcher: ^6.3.1

  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
